"""init tables

Revision ID: 4932081b5e4e
Revises: 
Create Date: 2025-12-04 16:39:03.528034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4932081b5e4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopping_lists_id', table_name='shopping_lists')
    op.drop_index('ix_shopping_lists_uid', table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index('ix_shopping_list_firebase_uid', table_name='shopping_list')
    op.drop_index('ix_shopping_list_id', table_name='shopping_list')
    op.drop_table('shopping_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('is_checked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shopping_list_pkey')
    )
    op.create_index('ix_shopping_list_id', 'shopping_list', ['id'], unique=False)
    op.create_index('ix_shopping_list_firebase_uid', 'shopping_list', ['firebase_uid'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shopping_lists_pkey')
    )
    op.create_index('ix_shopping_lists_uid', 'shopping_lists', ['uid'], unique=False)
    op.create_index('ix_shopping_lists_id', 'shopping_lists', ['id'], unique=False)
    # ### end Alembic commands ###
